/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pFormularios;
import pFormularios.MenuPrincipal;

/**
 *
 * @author walte
 */
public class AyudaCajero extends javax.swing.JFrame {

    /**
     * Creates new form AyudaCajero
     */
    public AyudaCajero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        bntRegreso = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 204, 51));
        jLabel8.setText("COMO ENTRAR AL REGISTRO DE COMPRAS?");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 10, 540, 50);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pImagenes/Flecha4.png"))); // NOI18N
        jPanel2.add(jLabel10);
        jLabel10.setBounds(160, 70, 120, 90);

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 204, 0));
        jLabel11.setText("Aquí podras ingresar al LOGIN ! ");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(30, 150, 410, 60);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pImagenes/menu 1 principal.png"))); // NOI18N
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 70, 410, 340);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 0));
        jLabel3.setText("COMO USAR EL LOGIN ?");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(660, 70, 300, 60);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("Primero necesitas obtener un USUARIO y CONTRASEÑA , que serean brindadas por el gerente.");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(520, 140, 600, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pImagenes/Flecha4.png"))); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(840, 360, 130, 110);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 0));
        jLabel4.setText("Ingrese la CONTRASEÑA designada");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(950, 390, 230, 60);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pImagenes/Flecha4.png"))); // NOI18N
        jPanel2.add(jLabel6);
        jLabel6.setBounds(820, 270, 130, 110);
        jPanel2.add(jLabel13);
        jLabel13.setBounds(610, 90, 330, 110);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pImagenes/LOGIN CAP.jpg"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(460, 260, 480, 250);

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 204, 0));
        jLabel7.setText("Ingrese el USUARIO designado");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(940, 300, 200, 60);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pImagenes/Blurry_blue_background-Theme_HD_Wallpaper_1920x1200.jpg"))); // NOI18N
        jPanel2.add(jLabel12);
        jLabel12.setBounds(0, 0, 1210, 650);

        jTabbedPane1.addTab("INICIO", jPanel2);

        jPanel3.setLayout(null);

        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 204, 51));
        jLabel16.setText("REGISTRA LOS DATOS CORRESPONDIENTES ");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(10, 10, 420, 40);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pImagenes/CAJONES.png"))); // NOI18N
        jPanel3.add(jLabel17);
        jLabel17.setBounds(20, 50, 1170, 320);

        jLabel18.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 204, 0));
        jLabel18.setText("LOS DATOS VALIDOS A INGRESAR SON : NOMBRE  DEL PRODUCTO , NOMBRE CLIENTE Y CANTIDAD ");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(100, 370, 920, 40);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pImagenes/combobox.jpg"))); // NOI18N
        jPanel3.add(jLabel19);
        jLabel19.setBounds(50, 410, 310, 220);

        jLabel20.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 204, 0));
        jLabel20.setText("PUEDE SELECCIONAR UN PRODUCTO PARA SU PROXIMA VENTA ");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(380, 500, 790, 30);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pImagenes/Blurry_blue_background-Theme_HD_Wallpaper_1920x1200.jpg"))); // NOI18N
        jPanel3.add(jLabel14);
        jLabel14.setBounds(0, 0, 1220, 640);

        jTabbedPane1.addTab("REGISTRO", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 20, 1220, 680);

        bntRegreso.setText("REGRESAR AL MENU PRINCIPAL");
        bntRegreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRegresoActionPerformed(evt);
            }
        });
        getContentPane().add(bntRegreso);
        bntRegreso.setBounds(963, 7, 240, 23);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pImagenes/Blurry_blue_background-Theme_HD_Wallpaper_1920x1200.jpg"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(0, 0, 1240, 690);

        setSize(new java.awt.Dimension(1253, 728));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bntRegresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRegresoActionPerformed
        MenuPrincipal GN = new MenuPrincipal();
          GN.setVisible(true);
            dispose();
    }//GEN-LAST:event_bntRegresoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AyudaCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AyudaCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AyudaCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AyudaCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AyudaCajero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntRegreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
